<?php

// $Id$

/**
 * @file
 *
 */
module_load_include('inc', 'islandora_form_builder', 'Utilities');

/**
 * Respond to menu hook.
 *
 * This hook is invoked from hook_menu().
 *
 * @ingroup menu_api_hooks
 * @ingroup hooks
 */
function islandora_form_builder_menu() {
  $items = array();

  $items['formbuilder/ingest'] = array(// Discuss urls at a later date.
    'title' => t('Ingest Form'),
    'page callback' => 'islandora_form_builder_ingest',
    'type' => MENU_CALLBACK,
    'access arguments' => array('add fedora datastreams')
  );

  $items['formbuilder/edit'] = array(// Discuss urls at a later date.
    'title' => t('Edit Form'),
    'page callback' => 'islandora_form_builder_edit',
    'type' => MENU_CALLBACK,
    'access arguments' => array('edit fedora meta data')
  );
  return $items;
}

/**
 *
 * @param string $collection_pid
 * @param string $collection_label
 * @return array
 */
function islandora_form_builder_ingest($collection_pid = NULL, $collection_label = NULL) {
  try {
    if ($collection_pid == NULL) {
      $collection_pid = variable_get('fedora_repository_pid', 'islandora:top');
    }
    $collection_pid = islandora_form_builder_validate_url_argument_collection_pid($collection_pid);
    if ($collection_pid !== FALSE) {
      islandora_form_builder_set_bread_crumbs($collection_pid);
      return drupal_get_form('islandora_form_builder_ingest_form', $collection_pid, $collection_label);
    }
    else {
      drupal_not_found();
    }
  } catch (Exception $e) {
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
  }
}

/**
 *
 * @param array $form_state
 * @param string $collection_pid
 * @param string $collection_label
 * @return array
 */
function islandora_form_builder_ingest_form(&$form_state, $collection_pid, $collection_label = NULL) {
  try {
    module_load_include('inc', 'islandora_form_builder', 'IngestFormBuilder');
    $ingest_form_builder = new IngestFormBuilder($form_state, $collection_pid, $collection_label);
    $form = $ingest_form_builder->createForm();
    return $form;
  } catch (Exception $e) {
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
    return array();
  }
}

/**
 *
 * @param array $form
 * @param array $form_state
 */
function islandora_form_builder_ingest_form_validate(&$form, &$form_state) {
  try {
    /*
     * Only validate the form if the submit button was pressed
     * (other buttons may be used for AHAH)
     */
    if ($form_state['clicked_button']['#id'] != 'edit-submit')
      return;
    module_load_include('inc', 'islandora_form_builder', 'IngestFormBuilder');
    $ingest_form_builder = new IngestFormBuilder($form_state);
    $ingest_form_builder->validateForm($form);
  } catch (Exception $e) {
    $form_state['rebuild'] = true;
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
  }
}

/**
 *
 * @param array $form
 * @param array $form_state
 * @return array
 */
function islandora_form_builder_ingest_form_submit(&$form, &$form_state) {
  try {
    /*
     * Only submit the form if the submit button was pressed
     * (other buttons may be used for AHAH)
     */
    if ($form_state['clicked_button']['#id'] != 'edit-submit')
      return;
    module_load_include('inc', 'islandora_form_builder', 'IngestFormBuilder');
    $ingest_form_builder = new IngestFormBuilder($form_state);
    $ingest_form_builder->submitForm($form);
  } catch (Exception $e) {
    $form_state['rebuild'] = true;
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
  }
}

/**
 * Menu Callback for the edit form.
 *
 * @param string $pid
 *   Object PID.
 * 
 * @return array
 *   A drupal form, used to edit the object $pid and the datastream $dsid.
 */
function islandora_form_builder_edit($pid = NULL, $form_name = NULL) {
  try {
    if (islandora_form_builder_check_edit_form_arguments_and_permissions($pid, $form_name)) {
      islandora_form_builder_set_bread_crumbs($pid);
      return drupal_get_form('islandora_form_builder_edit_form', $pid, $form_name);
    }
    else {
      drupal_not_found();
    }
  } catch (Exception $e) {
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
  }
}

/**
 *
 * @param array $form_state
 * @param string $pid
 * @param string $dsid
 * @return array 
 */
function islandora_form_builder_edit_form(&$form_state, $pid, $form_name) {
  try {
    module_load_include('inc', 'islandora_form_builder', 'EditFormBuilder');
    $edit_form_builder = new EditFormBuilder($form_state, $pid, $form_name);
    $form = $edit_form_builder->createForm();
    return $form;
  } catch (Exception $e) {
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
    return array();
  }
}

/**
 *
 * @param array $form
 * @param array $form_state
 */
function islandora_form_builder_ingest_edit_form_validate(&$form, &$form_state) {
  try {
    /*
     * Only validate the form if the submit button was pressed
     * (other buttons may be used for AHAH)
     */
    if ($form_state['clicked_button']['#id'] != 'edit-submit')
      return;
    module_load_include('inc', 'islandora_form_builder', 'EditFormBuilder');
    $edit_form_builder = new EditFormBuilder($form_state);
    $edit_form_builder->validateForm($form);
  } catch (Exception $e) {
    $form_state['rebuild'] = true;
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}"; 
    drupal_set_message($msg, 'error');
  }
}

/**
 *
 * @param array $form
 * @param array $form_state
 */
function islandora_form_builder_ingest_edit_form_submit(&$form, &$form_state) {
  try {
    /*
     * Only submit the form if the submit button was pressed
     * (other buttons may be used for AHAH)
     */
    if ($form_state['clicked_button']['#id'] != 'edit-submit')
      return;
    module_load_include('inc', 'islandora_form_builder', 'EditFormBuilder');
    $edit_form_builder = new EditFormBuilder($form_state);
    $edit_form_builder->submitForm($form);
  } catch (Exception $e) {
    $form_state['rebuild'] = true;
    $msg = "File: {$e->getFile()}<br/>Line: {$e->getLine()}<br/>Error: {$e->getMessage()}";
    drupal_set_message($msg, 'error');
  }
}